apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      name: client
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: http
      port: 8123
      targetPort: 8123
